### ISSUE TITLE
Generators page is not loading 

### ISSUE THREAD

**Issue by sonyccd** [yeoman/yeoman.github.io#698] opened 2016-11-25 18:49 UTC
<img width="1440" alt="screen shot 2016-11-25 at 1 41 29 pm" src="https://cloud.githubusercontent.com/assets/4007257/20633557/ef60365a-b315-11e6-9d2f-bbad236f1046.png">

**Comment by SBoudrias** [comment] 2016-11-25 19:31
Duplicate of #645

**Closed by SBoudrias** 2016-11-25 19:31 UTC
Labels: bug
