### ISSUE TITLE
bootstrap.css file is not included in index.html page initially.

### ISSUE THREAD

**Issue by yingdi11** [yeoman/yeoman.github.io#620] opened 2016-03-20 18:45 UTC
when I reached step 5 in the instruction page.I did not see the button for splendid.I look into the source code.I realized bower_components/bootstrap/dist/css/bootstrap.css is not included in the index file.

I follow the instruction in this page :+1: http://yeoman.io/codelab/preview-inbrowser.html.

Thanks!

**Comment by coffeejunk** [comment] 2016-04-03 10:27
this appears to be an issue with [bootstrap's `bower.json`](https://github.com/yeoman/generator-angular/issues/1116). The (quick)fix for this is adding this to your `bower.json`

```json
"overrides": {
  "bootstrap": {
    "main": [
      "dist/js/bootstrap.js",
      "dist/css/bootstrap.css",
      "less/bootstrap.less"
    ]
  }
}
```

**Comment by eddiemonge** [comment] 2016-04-08 19:38
its a bug in generator that was caused by the bootstrap team

**Closed by eddiemonge** 2016-04-08 19:38 UTC
